# Generated by Django 4.2 on 2023-04-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_cirado_em_remove_user_modificado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idade',
            field=models.IntegerField(),
        ),
    ]
